# Generated by Django 5.1 on 2024-12-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_task_order_alter_task_team"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("active", "Active"),
                    ("closed", "Closed"),
                ],
                default="pending",
                max_length=11,
            ),
        ),
    ]
